[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/template',
    'pallets/rewardcoin',
    'pallets/identitysel',
    'pallets/loose',
    'pallets/tight',
    'pallets/docverify',
    'runtime',
]
